### ISSUE TITLE
destination file is not rebuilded after change

### ISSUE THREAD

**Issue by zajca** [Craga89/gulp-watch-less#2]
I have this less task, watchLess works fine in console there is event that file changed but there is no change in destination files. Did I miss something?

```
lessFiles = ["./frontend-src/frontend-src/frontend.less","./frontend-src/admin-src/admin.less"]

gulp.task 'watch-less', ['sprite'],->
  gulp.src(lessFiles)
  .pipe(watchLess(lessFiles))
  .pipe(sourcemaps.init())
  .pipe(less().on('error', handleErrors))
  .pipe(sourcemaps.write())
  .pipe(gulp.dest('./web/assets/css'))
  .pipe(livereload())
  return
```

**Comment by treshugart** [comment]
Yup, same here. I copied the code example verbatim, only changing the paths.

**Comment by achtan** [comment]
same issue here

**Comment by treshugart** [comment]
Anyone experiencing my issue can temporarily use my fork if the need to.

**Comment by zajca** [comment]
@Craga89 Are you going to maintain this repository?

**Comment by gswalden** [comment]
thanks @treshugart, hopefully the main repo is updated soon

**Comment by treshugart** [comment]
No probs. There hasn't been any movement on my PRs yet :(
